name: tests

on: push

jobs:

  Compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compilation
        run: |
          mkdir build
          cd build
          cmake ..
          make

  Test_Add:
    needs: Compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Add
        run: |
          mkdir build && cd build && cmake .. && make
          ctest -R test_add --output-on-failure

  Test_Sub:
    needs: Compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Sub
        run: |
          mkdir build && cd build && cmake .. && make
          ctest -R test_sub --output-on-failure

  Test_Mul:
    needs: Compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Mul
        run: |
          mkdir build && cd build && cmake .. && make
          ctest -R test_mul --output-on-failure

  Test_Div:
    needs: Compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Div
        run: |
          mkdir build && cd build && cmake .. && make
          ctest -R test_div --output-on-failure

  Test_car:
    needs: Compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Car
        run: |
          mkdir build && cd build && cmake .. && make
          ctest -R test_car --output-on-failure

  Deployment:
    needs: [Test_Add, Test_Sub, Test_Mul, Test_Div, Test_car]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Déploiement de la solution"
